# Generated by Django 6.0.5 on 2026-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalements',
            old_name='etat',
            new_name='statut',
        ),
        migrations.AlterField(
            model_name='signalements',
            name='titre',
            field=models.CharField(help_text='Entrez le titre du signalement', max_length=200),
        ),
    ]
