# Generated by Django 6.0.7 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0003_rename_etat_signalements_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalements',
            name='analyse_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
