# Generated by Django 6.0.7 on 2026-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0004_signalements_analyse_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalements',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
