# Generated by Django 6.0.5 on 2026-07-18 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=250)),
                ('contenu', models.TextField()),
                ('type_ressource', models.CharField(choices=[('guide', 'Guide'), ('livre', 'Livre'), ('publication', 'Publication'), ('ressource', 'Ressource'), ('autre', 'Autre')], default='ressource', max_length=20)),
                ('acteur', models.CharField(choices=[('autorite', 'Autorité'), ('ong', 'ONG'), ('ecole', 'École'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
