# Generated by Django 6.0.7 on 2026-07-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('signalements', '0003_rename_etat_signalements_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='signalement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signalements.signalements'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='titre',
            field=models.CharField(default='Notification', max_length=200),
            preserve_default=False,
        ),
    ]
