# Generated by Django 6.0.7 on 2026-07-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_signalement_notifications_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
